POST https://trackapi.nutritionix.com/v2/natural/nutrients
x-app-id: 4751e5d2
x-app-key: 39ecf2def220b623feeb16ac509e09f1
x-remote-user-id: 0
Content-Type: application/json

{
    "query":"2 teaspoon of salt",
    "timezone": "US/Eastern"
}